# Generated by Django 4.1.4 on 2022-12-26 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("account_numer", models.CharField(max_length=255, unique=True)),
                ("account_name", models.CharField(max_length=255, unique=True)),
                ("account_description", models.TextField(max_length=500)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("encaissement", "encaissement"),
                            ("decaissement", "decaissement"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
