# Generated by Django 4.1.4 on 2022-12-27 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0002_rename_account_numer_main_account_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Additional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("account_number", models.CharField(max_length=255, unique=True)),
                ("account_name", models.CharField(max_length=255, unique=True)),
                ("account_description", models.TextField(max_length=500)),
                (
                    "account_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.main",
                    ),
                ),
            ],
        ),
    ]
