# Generated by Django 4.1.4 on 2022-12-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0003_additional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additional",
            name="account_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.main",
            ),
        ),
    ]
