# Generated by Django 4.1.4 on 2022-12-28 00:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0004_alter_additional_account_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("plan_at", models.DateField()),
                ("warning_at", models.IntegerField()),
                (
                    "accounting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.additional",
                    ),
                ),
            ],
        ),
    ]
