# Generated by Django 4.1.4 on 2022-12-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0006_fiscalyear_budget_fiscal_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalyear",
            name="year",
            field=models.IntegerField(unique=True),
        ),
    ]
