# Generated by Django 4.1.4 on 2022-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0008_fiscalyear_is_closed_fiscalyear_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="plan_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
