# Generated by Django 4.1.4 on 2022-12-29 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0009_alter_budget_plan_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adjunct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("account_name", models.CharField(max_length=255, unique=True)),
                (
                    "account_additional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.additional",
                    ),
                ),
            ],
        ),
    ]
