# Generated by Django 4.1.4 on 2023-01-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0011_rename_account_name_adjunct_adjunct_account_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additional",
            name="account_description",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="account_description",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
