# Generated by Django 4.1.4 on 2023-01-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0012_alter_additional_account_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additional",
            name="account_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="main",
            name="account_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
