# Generated by Django 4.1.4 on 2023-01-09 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0013_alter_additional_account_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additional",
            name="account_main",
            field=models.ForeignKey(
                default=str,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.main",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adjunct",
            name="account_additional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.additional",
            ),
        ),
    ]
