# Generated by Django 4.1.4 on 2023-01-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0014_alter_additional_account_main_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="budget", name="fiscal_year",),
    ]
