# Generated by Django 4.1.4 on 2023-01-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0015_remove_budget_fiscal_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="warning_at",
            field=models.IntegerField(default=0),
        ),
    ]
