# Generated by Django 4.1.4 on 2023-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0016_alter_budget_warning_at"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("accounting", "plan_at"), name="unique_budget"
            ),
        ),
    ]
