# Generated by Django 4.1.4 on 2023-03-03 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0017_budget_unique_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitoring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("warn_at", models.FloatField()),
                (
                    "accounting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.additional",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.fiscalyear",
                    ),
                ),
            ],
        ),
    ]
