# Generated by Django 4.1.4 on 2023-03-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0018_monitoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoring",
            name="message",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
