# Generated by Django 4.1.4 on 2023-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0019_monitoring_message"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="monitoring",
            constraint=models.UniqueConstraint(
                fields=("accounting", "year"), name="unique_alert"
            ),
        ),
    ]
