# Generated by Django 4.1.4 on 2023-03-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0020_monitoring_unique_alert"),
    ]

    operations = [
        migrations.RemoveField(model_name="budget", name="warning_at",),
    ]
