# Generated by Django 4.1.4 on 2023-04-09 00:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=255, null=True)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomerBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255, null=True)),
                ("bill_at", models.DateField()),
                ("deadline_at", models.DateField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255, null=True)),
                ("paying_reference", models.CharField(max_length=255, null=True)),
                ("bank_account_number", models.CharField(max_length=255, null=True)),
                ("bill_at", models.DateField()),
                ("accounting_date", models.DateField()),
                ("deadline_at", models.DateField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.plan",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
