# Generated by Django 4.1.4 on 2023-04-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("accounting", "0002_initial"),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierbill",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.currency",
            ),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="entry",
            field=models.ManyToManyField(to="billing.billentry"),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.partner",
            ),
        ),
        migrations.AddField(
            model_name="customerbill",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounting.plan"
            ),
        ),
        migrations.AddField(
            model_name="customerbill",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.currency",
            ),
        ),
        migrations.AddField(
            model_name="customerbill",
            name="entry",
            field=models.ManyToManyField(to="billing.billentry"),
        ),
        migrations.AddField(
            model_name="customerbill",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.partner",
            ),
        ),
        migrations.AddField(
            model_name="billentry",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.plan",
            ),
        ),
        migrations.AddField(
            model_name="billentry",
            name="tax",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.tax",
            ),
        ),
    ]
