# Generated by Django 4.1.4 on 2023-04-11 00:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
        ("treasury", "0004_accountingentry_is_verified"),
        ("billing", "0004_customerbill_is_lettered_supplierbill_is_lettered"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierBillPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("paid_at", models.DateField()),
                ("amount", models.FloatField()),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.plan",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currency",
                    ),
                ),
                (
                    "ref_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.supplierbill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerBillPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("paid_at", models.DateField()),
                ("amount", models.FloatField()),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.plan",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currency",
                    ),
                ),
                (
                    "ref_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.customerbill",
                    ),
                ),
            ],
        ),
    ]
