# Generated by Django 4.1.4 on 2023-04-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_customerbill_amount_foreign_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerbill",
            old_name="amount_foreign_currency",
            new_name="amount_foreign",
        ),
        migrations.RenameField(
            model_name="customerbillpayment",
            old_name="amount_foreign_currency",
            new_name="amount_foreign",
        ),
        migrations.RenameField(
            model_name="supplierbill",
            old_name="amount_foreign_currency",
            new_name="amount_foreign",
        ),
        migrations.RenameField(
            model_name="supplierbillpayment",
            old_name="amount_foreign_currency",
            new_name="amount_foreign",
        ),
    ]
