# Generated by Django 4.1.4 on 2023-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0009_rename_amount_foreign_currency_customerbill_amount_foreign_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbill",
            name="entry",
            field=models.ManyToManyField(
                blank=True, related_name="customer_bill_entry", to="billing.billentry"
            ),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="entry",
            field=models.ManyToManyField(
                blank=True, related_name="supplier_bill_entry", to="billing.billentry"
            ),
        ),
    ]
