# Generated by Django 4.1.4 on 2023-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_alter_customerbill_entry_alter_supplierbill_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbill",
            name="amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="customerbill",
            name="entry",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="customer_bill_entry",
                to="billing.billentry",
            ),
        ),
    ]
