# Generated by Django 4.1.4 on 2023-04-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0012_rename_billentry_billline_remove_customerbill_entry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbill",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerbill",
            name="amount_foreign",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerbill",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customerbill",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.partner",
            ),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbill",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.partner",
            ),
        ),
    ]
