# Generated by Django 4.1.4 on 2023-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_alter_customerbill_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbill",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
