# Generated by Django 4.1.4 on 2023-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_customerbill_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerbill",
            name="bill_lines",
            field=models.ManyToManyField(
                blank=True, related_name="customer_bill_lines", to="billing.billline"
            ),
        ),
    ]
