# Generated by Django 4.1.4 on 2023-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_alter_customerbill_bill_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbill",
            name="can_edit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="can_edit",
            field=models.BooleanField(default=True),
        ),
    ]
