# Generated by Django 4.1.4 on 2023-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_customerbill_can_edit_supplierbill_can_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="tax_amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
