# Generated by Django 4.1.4 on 2023-04-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_tax_currency"),
        ("billing", "0017_billline_tax_amount"),
    ]

    operations = [
        migrations.RemoveField(model_name="billline", name="tax",),
        migrations.AddField(
            model_name="billline",
            name="tax",
            field=models.ManyToManyField(to="accounting.tax"),
        ),
    ]
