# Generated by Django 4.1.4 on 2023-04-18 23:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_tax_currency"),
        ("billing", "0018_remove_billline_tax_billline_tax"),
    ]

    operations = [
        migrations.RemoveField(model_name="billline", name="tax",),
        migrations.RemoveField(model_name="billline", name="tax_amount",),
        migrations.CreateModel(
            name="BillLineTax",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("tax_amount", models.FloatField()),
                (
                    "bill_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.billline",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounting.tax"
                    ),
                ),
            ],
        ),
    ]
