# Generated by Django 4.1.4 on 2023-04-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_remove_billline_tax_remove_billline_tax_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customerbill", name="bill_lines",),
        migrations.RemoveField(model_name="supplierbill", name="bill_lines",),
        migrations.AddField(
            model_name="billline",
            name="customer_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.customerbill",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="supplier_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.supplierbill",
            ),
        ),
    ]
