# Generated by Django 4.1.4 on 2023-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_remove_customerbill_bill_lines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="price_with_tax",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
