# Generated by Django 4.1.4 on 2023-04-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_billline_price_with_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billlinetax",
            name="bill_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill_line_tax_amount",
                to="billing.billline",
            ),
        ),
    ]
