# Generated by Django 4.1.4 on 2023-05-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_alter_billlinetax_bill_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerbill", old_name="can_edit", new_name="is_draft",
        ),
        migrations.RenameField(
            model_name="partner", old_name="state", new_name="bank_iban",
        ),
        migrations.RenameField(
            model_name="supplierbill", old_name="can_edit", new_name="is_draft",
        ),
        migrations.AddField(
            model_name="billline",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerbill",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="bank_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="bank_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="bank_swift_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="municipality",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="quarter",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="street_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="supplierbill",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
