# Generated by Django 4.1.4 on 2023-04-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_alter_journal_type_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="type_journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_journal",
                to="settings.journaltype",
            ),
        ),
    ]
