# Generated by Django 4.1.4 on 2023-04-09 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                (
                    "country_code",
                    models.CharField(
                        choices=[("us", "us"), ("cd", "cd"), ("eur", "eur")],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("is_local", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyDailyRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("rate", models.IntegerField()),
                ("rate_at", models.DateField(auto_now=True, unique=True)),
                ("in_use", models.BooleanField(default=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_currency",
                        to="treasury.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_currency",
                        to="treasury.currency",
                    ),
                ),
            ],
            options={"db_table": "currency_daily_rate",},
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("reference", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255, null=True)),
                ("transaction_at", models.DateField()),
                ("amount", models.FloatField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.plan",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currency",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.partner",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("slip_number", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("out_at", models.DateField()),
                ("write_at", models.DateTimeField(auto_now=True)),
                ("more", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "accounting_additional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.additional",
                    ),
                ),
                (
                    "accounting_adjunct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.adjunct",
                    ),
                ),
                (
                    "accounting_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.main",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.currency",
                    ),
                ),
                (
                    "daily_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currencydailyrate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("slip_number", models.CharField(max_length=255, null=True)),
                ("amount", models.FloatField()),
                ("in_at", models.DateField()),
                ("write_at", models.DateTimeField(auto_now=True)),
                ("more", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "accounting_additional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.additional",
                    ),
                ),
                (
                    "accounting_adjunct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.adjunct",
                    ),
                ),
                (
                    "accounting_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.main",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.currency",
                    ),
                ),
                (
                    "daily_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currencydailyrate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountingEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("rate", models.IntegerField(default=1)),
                ("slip", models.CharField(max_length=20)),
                ("slip_number", models.CharField(max_length=255, null=True)),
                ("label", models.CharField(max_length=255, null=True)),
                ("tier", models.CharField(max_length=255, null=True)),
                ("date_at", models.DateField()),
                ("debit", models.DecimalField(decimal_places=2, max_digits=20)),
                ("credit", models.DecimalField(decimal_places=2, max_digits=20)),
                ("write_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.plan",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.currency",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "accounting_entry",},
        ),
    ]
