# Generated by Django 4.1.4 on 2023-04-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="rate",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
