# Generated by Django 4.1.4 on 2022-12-30 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0011_rename_account_name_adjunct_adjunct_account_name"),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="country_iso",
            field=models.CharField(
                choices=[("us", "us"), ("cod", "cod"), ("eur", "eur")],
                max_length=3,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("slip_number", models.CharField(max_length=255, unique=True)),
                ("amount", models.FloatField()),
                ("out_at", models.DateField()),
                ("more", models.CharField(max_length=255, null=True)),
                (
                    "accounting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.additional",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.currency",
                    ),
                ),
                (
                    "rate_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currencydailyrate",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting_plan.adjunct",
                    ),
                ),
            ],
        ),
    ]
