# Generated by Django 4.1.4 on 2022-12-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0002_alter_currency_country_iso_outcome"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outcome", old_name="rate_used", new_name="daily_rate",
        ),
    ]
