# Generated by Django 4.1.4 on 2023-04-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0003_remove_accountingentry_slip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingentry",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
