# Generated by Django 4.1.4 on 2023-01-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0011_rename_account_name_adjunct_adjunct_account_name"),
        ("treasury", "0003_rename_rate_used_outcome_daily_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outcome",
            old_name="accounting",
            new_name="accounting_additional",
        ),
        migrations.RenameField(
            model_name="outcome", old_name="tag", new_name="accounting_adjunct",
        ),
        migrations.AddField(
            model_name="outcome",
            name="accounting_main",
            field=models.ForeignKey(
                default=str,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.main",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="currency",
            name="country_iso",
            field=models.CharField(
                choices=[("us", "us"), ("cd", "cd"), ("eur", "eur")],
                max_length=3,
                unique=True,
            ),
        ),
    ]
