# Generated by Django 4.1.4 on 2023-04-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_customerbill_amount_foreign_currency_and_more"),
        ("treasury", "0004_accountingentry_is_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountingentry",
            options={"verbose_name_plural": "Accounting_entries"},
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_billing_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.customerbill",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_billing_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="billing.supplierbill",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="treasury.statement",
            ),
        ),
    ]
