# Generated by Django 4.1.4 on 2023-01-06 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0011_rename_account_name_adjunct_adjunct_account_name"),
        ("treasury", "0004_rename_accounting_outcome_accounting_additional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outcome",
            name="write_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "slip_number",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("amount", models.FloatField()),
                ("in_at", models.DateField()),
                ("write_at", models.DateTimeField(auto_now=True)),
                ("more", models.CharField(max_length=255, null=True)),
                (
                    "accounting_additional",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.additional",
                    ),
                ),
                (
                    "accounting_adjunct",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting_plan.adjunct",
                    ),
                ),
                (
                    "accounting_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting_plan.main",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="treasury.currency",
                    ),
                ),
                (
                    "daily_rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="treasury.currencydailyrate",
                    ),
                ),
            ],
        ),
    ]
