# Generated by Django 4.1.4 on 2023-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0005_outcome_write_at_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="slip_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="slip_number",
            field=models.CharField(max_length=255),
        ),
    ]
