# Generated by Django 4.1.4 on 2023-04-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_customerbill_amount_foreign_currency_and_more"),
        ("treasury", "0005_alter_accountingentry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="credit",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="debit",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.partner",
            ),
        ),
    ]
