# Generated by Django 4.1.4 on 2023-04-12 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_customerbill_amount_foreign_currency_and_more"),
        ("accounting", "0002_initial"),
        ("treasury", "0006_alter_accountingentry_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="accounting.plan",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency",
                to="treasury.currency",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner",
                to="billing.partner",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_billing_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_billing_customer",
                to="billing.customerbill",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_billing_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_billing_supplier",
                to="billing.supplierbill",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_statement",
                to="treasury.statement",
            ),
        ),
    ]
