# Generated by Django 4.1.4 on 2023-01-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0017_budget_unique_budget"),
        ("treasury", "0007_alter_outcome_daily_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="accounting_additional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.additional",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="accounting_adjunct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting_plan.adjunct",
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="accounting_additional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.additional",
            ),
        ),
    ]
