# Generated by Django 4.1.4 on 2023-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0007_alter_accountingentry_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingentry",
            name="amount_foreign",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
