# Generated by Django 4.1.4 on 2023-01-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting_plan", "0017_budget_unique_budget"),
        ("treasury", "0008_alter_income_accounting_additional_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="more",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="accounting_additional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting_plan.additional",
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="accounting_adjunct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting_plan.adjunct",
            ),
        ),
        migrations.AlterField(
            model_name="outcome",
            name="more",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
