# Generated by Django 4.1.4 on 2023-04-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0008_accountingentry_amount_foreign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="credit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="debit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
