# Generated by Django 4.1.4 on 2023-04-13 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_alter_customerbill_entry_alter_supplierbill_entry"),
        ("accounting", "0002_initial"),
        ("treasury", "0009_alter_accountingentry_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_entry",
                to="accounting.plan",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_entry",
                to="treasury.currency",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_entry",
                to="billing.partner",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_billing_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_billing_customer_entry",
                to="billing.customerbill",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_billing_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_billing_supplier_entry",
                to="billing.supplierbill",
            ),
        ),
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_statement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_statement_entry",
                to="treasury.statement",
            ),
        ),
        migrations.CreateModel(
            name="CurrencyDiffrenceRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_currency_difference_rate",
                        to="accounting.plan",
                    ),
                ),
                (
                    "diff_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_difference_category",
                        to="accounting.plancategory",
                    ),
                ),
            ],
        ),
    ]
