# Generated by Django 4.1.4 on 2023-04-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_alter_customerbill_amount_and_more"),
        ("treasury", "0010_alter_accountingentry_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="statement",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.partner",
            ),
        ),
    ]
