# Generated by Django 4.1.4 on 2023-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0011_alter_statement_label_alter_statement_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="can_edit",
            field=models.BooleanField(default=True),
        ),
    ]
