# Generated by Django 4.1.4 on 2023-04-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_customerbill_can_edit_supplierbill_can_edit"),
        ("treasury", "0012_statement_can_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingentry",
            name="ref_bill_line",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_bill_line_entry",
                to="billing.billline",
            ),
        ),
    ]
