# Generated by Django 4.1.4 on 2023-04-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_alter_billlinetax_bill_line"),
        ("treasury", "0013_accountingentry_ref_bill_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="ref_bill_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_bill_line_entry",
                to="billing.billline",
            ),
        ),
    ]
