# Generated by Django 4.1.4 on 2023-05-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0014_alter_accountingentry_ref_bill_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statement", old_name="can_edit", new_name="is_draft",
        ),
        migrations.AddField(
            model_name="statement",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
