# Generated by Django 4.1.4 on 2023-04-09 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Additional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("account_number", models.CharField(max_length=255, unique=True)),
                ("account_name", models.CharField(max_length=255, unique=True)),
                (
                    "account_description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adjunct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("adjunct_account_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("plan_at", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("rate", models.IntegerField()),
                ("is_closed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("account_number", models.CharField(max_length=255, unique=True)),
                ("account_name", models.CharField(max_length=255, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("encaissement", "encaissement"),
                            ("decaissement", "decaissement"),
                        ],
                        max_length=255,
                    ),
                ),
                ("account_classification", models.CharField(max_length=255)),
                (
                    "account_description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("can_credit", models.BooleanField(default=False)),
                ("can_debit", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Monitoring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("warn_at", models.FloatField()),
                ("message", models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=500)),
                ("allow_lettering", models.BooleanField(default=False)),
                (
                    "load_from",
                    models.CharField(
                        blank=True,
                        choices=[("csv", "csv"), ("excel", "excel")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={"db_table": "accounting_plan",},
            managers=[("manager", django.db.models.manager.Manager()),],
        ),
        migrations.CreateModel(
            name="PlanCategory",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "accounting_plan_category",},
        ),
        migrations.CreateModel(
            name="TaxCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.plan",
                    ),
                ),
                (
                    "calculation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounting.taxcalculation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="plancategory",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.plancategory",
            ),
        ),
    ]
