# Generated by Django 4.1.4 on 2023-04-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0011_alter_statement_label_alter_statement_partner"),
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="treasury.currency",
            ),
        ),
    ]
