# Generated by Django 4.1.4 on 2023-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_plan_currency"),
    ]

    operations = [
        migrations.RemoveField(model_name="tax", name="calculation",),
        migrations.AddField(
            model_name="tax",
            name="is_fixed",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="TaxCalculation",),
    ]
