# Generated by Django 4.1.4 on 2023-04-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_typetax_alter_tax_options_tax_type_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typetax", options={"verbose_name_plural": "Type taxes"},
        ),
    ]
