# Generated by Django 4.1.4 on 2023-04-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_alter_journal_type_journal"),
        ("accounting", "0006_alter_typetax_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="tax", name="type_tax",),
        migrations.AddField(
            model_name="tax",
            name="type_journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.journaltype",
            ),
        ),
        migrations.DeleteModel(name="TypeTax",),
    ]
