# Generated by Django 4.1.4 on 2023-04-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_alter_journal_type_journal"),
        ("accounting", "0007_remove_tax_type_tax_tax_type_journal_delete_typetax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="type_journal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_journal_type",
                to="settings.journaltype",
            ),
        ),
    ]
