# Generated by Django 4.1.4 on 2023-04-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0013_accountingentry_ref_bill_line"),
        ("accounting", "0009_tax_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="treasury.currency",
            ),
        ),
    ]
